# -*- coding: utf-8 -*-
"""기계학습프로그래밍_9_28_(2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YHA74g4Gi0URHoIAS1VyDF9r7MPui2Mz
"""

import pandas as pd
import seaborn as sns


columns = [
    'buying',
    'maint',
    'doors',
    'persons',
    'lug_boot',
    'safety',
    'class'
]


df = pd.read_csv('car.data', names=columns)


df.head(10)

# 다른방법
dt = pd.read_csv('car.data', names=columns)

dt.columns = ['buying',
    'maint',
    'doors',
    'persons',
    'lug_boot',
    'safety',
    'class']

dt.head(10)

X = df.drop("class",axis = 1)
y = df["class"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.preprocessing import LabelEncoder
label_encoders = {}
for column in columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

df

# 의사결정나무

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

pred_df = model.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred_df))

# 랜덤포레스트

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train,y_train)

pred_df = model.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred_df))

# 로지스틱회귀

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

pred_df = model.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred_df))