# -*- coding: utf-8 -*-
"""기계학습프로그래밍_9_28_(2)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YHA74g4Gi0URHoIAS1VyDF9r7MPui2Mz
"""

import pandas as pd
import seaborn as sns


columns = [
    'buying',
    'maint',
    'doors',
    'persons',
    'lug_boot',
    'safety',
    'class'
]


df = pd.read_csv('car.data', names=columns)


df.head(10)

# 다른방법
dt = pd.read_csv('car.data', names=columns)

dt.columns = ['buying',
    'maint',
    'doors',
    'persons',
    'lug_boot',
    'safety',
    'class']

dt.head(10)

X = df.drop("class",axis = 1)
y = df["class"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.preprocessing import LabelEncoder
label_encoders = {}
for column in columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

df

# 의사결정나무

from sklearn.tree import DecisionTreeClassifier
model_D = DecisionTreeClassifier()
model_D.fit(X_train, y_train)

pred_df_D = model_D.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred_df_D))

# 랜덤포레스트

from sklearn.ensemble import RandomForestClassifier
model_R = RandomForestClassifier()
model_R.fit(X_train,y_train)

pred_df_R = model_R.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred_df_R))

# 로지스틱회귀

from sklearn.linear_model import LogisticRegression
model_D = LogisticRegression()
model_D.fit(X_train,y_train)

pred_df_L = model_D.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, pred_df_L))

# 성능비교 와 평가지표

from sklearn.metrics import classification_report, confusion_matrix

# DecisionTree

print(classification_report(y_test, pred_df_D))

cmD = confusion_matrix(y_test,pred_df_D)
print(cmD)

# RandomForest

print(classification_report(y_test, pred_df_R))

cmR = confusion_matrix(y_test, pred_df_R)
print(cmR)

# LogisticRegression

print(classification_report(y_test, pred_df_L))

cmL = confusion_matrix(y_test, pred_df_L)
print(cmL)
