# -*- coding: utf-8 -*-
"""기계학습프로그래밍_9.14_(1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWCQpAYDukGrgbPA4JxO4XHd98RBKNHA
"""

import pandas as pd
df = pd.read_csv('iris.csv')
df.head(10)

#______________(1)"iris.csv"________________________

#1.DecisionTree

import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import classification_report



data = pd.read_csv("iris.csv")



X = df.drop("species", axis=1)

y = df["species"]



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)



model = DecisionTreeClassifier()



model.fit(X_train, y_train)



pred_dt = model.predict(X_test)

print(classification_report(y_test, pred_dt))

#2. Random Forest



from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

# 3. Logistic Regression



from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=200)

model.fit(X_train, y_train)

# 4. SVM

# SVM (Support Vector Machine)
# 클래스 사이의 경계(Margin)를 가장 크게 만드는 선/면을 찾는 방식입니다.
# 핵심 파라미터는 C, kernel, gamma입니다.
# 특히 데이터가 복잡하면 kernel='rbf'를 많이 씁니다.

from sklearn.model_selection import train_test_split

from sklearn.svm import SVC

# 5. KNN

# KNN (K-Nearest Neighbors)
# 새로운 데이터 주변의 가장 가까운 K개 데이터를 보고 다수결로 분류합니다.
# 핵심 파라미터는 n_neighbors입니다.

from sklearn.neighbors import KNeighborsClassifier



model = KNeighborsClassifier()

model.fit(X_train, y_train)

#______________(2)"diabetes.csv"________________________

df2 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/기계학습프로그래밍/diabetes.csv")
df2.head(10)

#1
from sklearn.model_selection import train_test_split

X = df2.drop("Glucose",axis=1)
y = df2["Glucose"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()


model.fit(X_train,y_train)



pred_dt = model.predict(X_test)

print(classification_report(y_test, pred_dt))

#2. Random Forest



from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

# 3. Logistic Regression



from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=200)

model.fit(X_train, y_train)

# 5. KNN

from sklearn.neighbors import KNeighborsClassifier



model = KNeighborsClassifier()

model.fit(X_train, y_train)