# -*- coding: utf-8 -*-
"""기계학습프로그래밍_9_21_리포트_wine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfx3FmjyX6ZU0tM5uOmzXh9NuBLR4gve

## 1. 필요한 라이브러리 불러오기
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

"""## 2. 데이터 불러오기"""

df = pd.read_csv("/content/wine.csv")
df

"""## 3. 데이터 구조 확인"""

print("데이터 크기:", df.shape)

print("\n처음 5개 데이터")
display(df.head())

print("\n변수 이름")
print(df.columns.tolist())

print("\n자료형")
print(df.dtypes)

print("\n데이터 정보")
df.info()

"""## 4. 결측치와 중복 데이터 확인"""

print("변수별 결측치 개수")
print(df.isnull().sum())

print("\n중복 행 개수")
print(df.duplicated().sum())

"""## 5. 분석 변수 지정"""

numeric_cols = [
    "Alcohol",
    "Malic.acid",
    "Ash",
    "Acl",
    "Mg",
    "Phenols",
    "Flavanoids",
    "Nonflavanoid.phenols",
    "Proanth",
    "Color.int",
    "Hue",
    "OD",
    "Proline"
]

target_col = "Wine"

"""## 6. 레이블 종류와 개수 확인"""

print("레이블 종류")
print(df[target_col].unique())

print("\n레이블별 개수")
print(df[target_col].value_counts())

df[target_col].value_counts()

plt.figure(figsize=(6, 4))

ax = sns.countplot(data=df, x=target_col)

for container in ax.containers:
    ax.bar_label(container)

plt.title("Number of Samples by Wine Class")
plt.xlabel("Wine Class")
plt.ylabel("Count")
plt.tight_layout()
plt.show()

"""## 7. 기술통계량 확인"""

display(df[numeric_cols].describe().round(3))

"""## 8. 와인 클래스별 평균과 표준편차 확인"""

print("와인 클래스별 평균")
display(
    df.groupby(target_col)[numeric_cols]
      .mean()
      .round(3)
)

print("와인 클래스별 표준편차")
display(
    df.groupby(target_col)[numeric_cols]
      .std()
      .round(3)
)

"""## 9. 각 변수의 전체 분포 확인"""

for col in numeric_cols:
    plt.figure(figsize=(7, 4))

    sns.histplot(
        data=df,
        x=col,
        bins=20,
        kde=True
    )

    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.tight_layout()
    plt.show()

"""## 10. 와인 클래스별 변수 분포 비교"""

for col in numeric_cols:
    plt.figure(figsize=(7, 4))

    sns.histplot(
        data=df,
        x=col,
        hue=target_col,
        kde=True,
        element="step",
        stat="density",
        common_norm=False
    )

    plt.title(f"{col} Distribution by Wine Class")
    plt.tight_layout()
    plt.show()

"""## 11. Box Plot"""

for col in numeric_cols:
    plt.figure(figsize=(7, 4))

    sns.boxplot(
        data=df,
        x=target_col,
        y=col
    )

    plt.title(f"{col} by Wine Class")
    plt.tight_layout()
    plt.show()

"""## 12. Violin Plot"""

for col in numeric_cols:
    plt.figure(figsize=(7, 4))

    sns.violinplot(
        data=df,
        x=target_col,
        y=col,
        inner="quartile"
    )

    plt.title(f"{col} Distribution by Wine Class")
    plt.tight_layout()
    plt.show()

"""## 13. Pair Plot"""

pair_cols = [
    "Alcohol",
    "Phenols",
    "Flavanoids",
    "Color.int",
    "OD",
    "Proline"
]

sns.pairplot(
    df,
    vars=pair_cols,
    hue=target_col,
    diag_kind="hist"
)

plt.show()

"""## 14. 변수 간 상관관계 분석"""

corr = df[numeric_cols].corr()

display(corr.round(3))

plt.figure(figsize=(12, 10))

sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    square=True
)

plt.title("Correlation Matrix")
plt.tight_layout()
plt.show()

"""## 15. 총 페놀과 플라보노이드의 관계"""

plt.figure(figsize=(7, 5))

sns.scatterplot(
    data=df,
    x="Phenols",
    y="Flavanoids",
    hue=target_col,
    s=70
)

plt.title("Phenols vs Flavanoids")
plt.xlabel("Phenols")
plt.ylabel("Flavanoids")
plt.tight_layout()
plt.show()

"""## 16. 알코올과 프롤린의 관계"""

plt.figure(figsize=(7, 5))

sns.scatterplot(
    data=df,
    x="Alcohol",
    y="Proline",
    hue=target_col,
    s=70
)

plt.title("Alcohol vs Proline")
plt.xlabel("Alcohol")
plt.ylabel("Proline")
plt.tight_layout()
plt.show()

"""## 17. IQR을 이용한 이상치 탐지"""

for col in numeric_cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)

    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    outliers = df[
        (df[col] < lower) |
        (df[col] > upper)
    ]

    print(
        f"{col:20s} : "
        f"{len(outliers)}개 "
        f"(Lower={lower:.2f}, Upper={upper:.2f})"
    )

for col in numeric_cols:
    q1 = df[col].quantile(0.25)
    q3 = df[col].quantile(0.75)

    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr

    outliers = df[
        (df[col] < lower) |
        (df[col] > upper)
    ]

    if len(outliers) > 0:
        print(f"\n[{col} 이상치]")
        display(outliers[[col, target_col]])

"""## 18. 와인 클래스별 평균값 비교"""

mean_long = (
    df.groupby(target_col)[numeric_cols]
      .mean()
      .reset_index()
      .melt(
          id_vars=target_col,
          var_name="Feature",
          value_name="Mean"
      )
)

plt.figure(figsize=(14, 6))

sns.barplot(
    data=mean_long,
    x="Feature",
    y="Mean",
    hue=target_col
)

plt.title("Mean Feature Values by Wine Class")
plt.xlabel("Feature")
plt.ylabel("Mean")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()