# -*- coding: utf-8 -*-
"""기계학습프로그래밍_9.14_(1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aWCQpAYDukGrgbPA4JxO4XHd98RBKNHA

##(1)iris.csv
"""

#1.DecisionTree

import pandas as pd
from sklearn.metrics import classification_report

df = pd.read_csv("iris.csv")

X = df.drop("species", axis=1)
y = df["species"]


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

pred_dt = model.predict(X_test)
print(classification_report(y_test, pred_dt))

#2. Random Forest

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)
pred_dt = model.predict(X_test)
print(classification_report(y_test, pred_dt))

# 3. Logistic Regression

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=200)

model.fit(X_train, y_train)
pred_dt = model.predict(X_test)
print(classification_report(y_test, pred_dt))

# 4. KNN

# KNN (K-Nearest Neighbors)
# 새로운 데이터 주변의 가장 가까운 K개 데이터를 보고 다수결로 분류합니다.
# 핵심 파라미터는 n_neighbors입니다.

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(X_train, y_train)
pred_dt = model.predict(X_test)
print(classification_report(y_test, pred_dt))

"""##(2)diabetes.csv"""

df2 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/기계학습프로그래밍/diabetes.csv")
df2.head(10)

#1. DecisionTree
from sklearn.model_selection import train_test_split

X = df2.drop("Glucose",axis=1)
y = df2["Glucose"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()


model.fit(X_train,y_train)


pred_dt = model.predict(X_test)

print(classification_report(y_test, pred_dt))

#2. Random Forest

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)
pred_dt = model.predict(X_test)
print(classification_report(y_test, pred_dt))

# 3. Logistic Regression



from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=200)

model.fit(X_train, y_train)
pred_dt = model.predict(X_test)
print(classification_report(y_test, pred_dt))

# 4. KNN

from sklearn.neighbors import KNeighborsClassifier



model = KNeighborsClassifier()

model.fit(X_train, y_train)
pred_dt = model.predict(X_test)
print(classification_report(y_test, pred_dt))

# Unseen data -> 보지 못한 데이터를 봤을때
# train &  generalization은 비례관계
# AGI = 추론보단 예측 (실제 사람과 같은 ai) , 단 ai는 추론이라 불리긴함


# 인간지능의 종류는 회귀(Regressor) or 분류(Classifier)
# 비지도학습이 더 선호되는 이유 -> 지도 학습의 레이블에 시간과 비용이 많이 듬
# 강화학습 = 알파고 (지도,비지도,강화)

# 모델이 데이터의 특성이 다 똑같지 않음 모델이 모든 데이터의 정확도를 위해 일반화가 필요함

"""## Regressor"""

df3 = df2.drop("Outcome",axis=1)

X = df3.drop("BMI",axis=1)
y = df3["BMI"]

from sklearn.model_selection import train_test_split


X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3)

# 1. DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(X_train,y_train)


y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print("Decision Tree MSE :", mse)

# 2. Random Forest Regressor

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)

print("Random Forest MSE :", mse)

# 3. Linear Regression
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)

print("Linear Regression MSE :", mse)

"""##(3)wine.csv"""

# Classifier

import pandas as pd

df4 = pd.read_csv("wine.csv")

X = df4.drop("Wine", axis=1)
y = df4["Wine"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

from sklearn.metrics import accuracy_score


# 1. Decision Tree
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("DT Accuracy :", accuracy_score(y_test, y_pred))


# 2. Random Forest
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("RF Accuracy :", accuracy_score(y_test, y_pred))


# 3. Logistic Regression
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("LR Accuracy :", accuracy_score(y_test, y_pred))


# 4. KNN
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("KNN Accuracy :", accuracy_score(y_test, y_pred))

# Regressor

df5 = df4.drop("Wine", axis=1)


X = df5.drop("Alcohol", axis=1)
y = df5["Alcohol"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

from sklearn.metrics import mean_squared_error



# 1. Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("DT MSE :", mean_squared_error(y_test, y_pred))


# 2. Random Forest Regressor
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("RF MSE :", mean_squared_error(y_test, y_pred))


# 3. Linear Regression
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("LR MSE :", mean_squared_error(y_test, y_pred))


# 4. KNN Regressor
from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor()

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("KNN MSE :", mean_squared_error(y_test, y_pred))









# 숙제(wine_data)
# 중간고사는 FAQ에서 나온다
# wine 삭제후 알콜을 레이블로 R D L(모델 3개)
# Classifier = accuracy
# Regresser = mse
# f1 recall , 1종오류 2종오류 상세히 시험문제